name: Build

on: [push, pull_request]

jobs:
  build-android-armv7a:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build android-armv7a
      run: |
        scripts/build-android-armv7a.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-armv7a-build
        path: build/

  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug --32bits --prefix=build/out/
        ./waf.bat install
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-i386-build
        path: build/out/
